name: "HammyRestart"
description: "Restart your server every X seconds"
version: "2.2.1"
author: "Hammynl"
main: "com.github.hammynl.restarter.Restarter"
api-version: "1.13"
commands:
  restarter:
    description: Shows a better help menu.
    usage: /restarter
    aliases: [hr, hammyrestart]

